### ISSUE TITLE
problem with connection was not closed during load test

### ISSUE THREAD

**Issue by justinhomes** [ziyasal/RepositoryT.EntityFramework#6]
I am using this with WCF and unity
   my IOC regestraion looks like this
```
 container.RegisterType<IDataContextFactory<DBDataContext>, DefaultDataContextFactory<DBDataContext>>(new HierarchicalLifetimeManager());
 container.RegisterType<IUnitOfWork, EfUnitOfWork<DBDataContext>>(new ContainerControlledLifetimeManager());

  container.RegisterType<ICustomerRepository, CustomerRepository>(new ContainerControlledLifetimeManager());
container.RegisterType<ICustomerService, CustomerService>(new ContainerControlledLifetimeManager());

container.RegisterType<IServiceLocator, ServiceLocator>(new ContainerControlledLifetimeManager());

```

this works if i make calls postman of some client like that but when i do a load test with soap ui for 60 sec with 5 sec interval 5 threads for same operations it starts to throw these errors

```
System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.InvalidOperationException: The connection was not closed. The connection's current state is connecting.
   at System.Data.ProviderBase.DbConnectionClosedConnecting.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityConnection.<Open>b__2()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
```

**Comment by ocinbat** [comment]
Hi @justinhomes .
It's not a bug.
You're trying to use a non thread safe object on multi threaded operations.
You should ask these questions on stackoverflow tho not here.
This section is for package related issues, not programming questions.
